### ISSUE TITLE
Logo and Visual Identity

### ISSUE THREAD

**Issue by Eugeniosales** [deeplearningunb/Skincare#10]
The visual identity aims to define the colors and the logo which is going to be used on the Frontend.

To be accepted, the visual identity must contain:
- [x] Logo for Skincare
- [x] Hexadecimal color palette to be used on the frontend

The task must be submitted on this issue on the comments.

**Comment by lgpinheiro94** [comment]
![skincare](https://user-images.githubusercontent.com/43656009/69060183-b36b1b80-09f5-11ea-82dd-b3f02d8cea57.png)
Galera, elaborei esse logo: 
Cores :
#ff5757 
#ffffff 
#474cd4 

Fonte: quiiicksand

**Comment by lgpinheiro94** [comment]
Pensei nesse logo galera, acho que as cores tem haver e podemos eleborar uma palheta mais variada, com vermelho, branco e preto, degradê, muita coisa pode ser feita, sugestões, duvidas e comentários, por favor

**Comment by lgpinheiro94** [comment]
![2](https://user-images.githubusercontent.com/43656009/69061912-d5b26880-09f8-11ea-954f-865613475a8d.png)

**Comment by lgpinheiro94** [comment]
Uma navbar tentando seguir os padrões de cor e design do projeto Skincare, que podem ser adaptados durante o projeto Skincare.

**Comment by Gustavo-Nogueira** [comment]
Perfeito.Ficou ótimo!
